version: '3.7'

services:
  ci:
    image: drone/drone:1.1.0
    container_name: drone_ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    env_file:
      - .env
    environment:
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=drone.ci.local
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=true
    ports:
      - 80:80
      - 443:443
